FROM wordpress:5.5.1-php7.4-apache
#FROM wordpress:5.1-php7.1-apache

# Install WP-CLI
RUN curl -o /bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x /bin/wp
