name: Plugin asset/readme update
on:
  push:
    branches:
      - master
jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          composer install --no-dev
          composer dump-autoload -o
          git config --global user.email "10upbot+github@10up.com"
          git config --global user.name "10upbot on GitHub"
          git add -f vendor && git commit -m "Add composer dependencies"
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ secrets.WORDPRESS_SLUG }}
