name: Deploy to WordPress.org
on:
  release:
    types: [published]
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          composer install --no-dev
          composer dump-autoload -o
          git config --global user.email "10upbot+github@10up.com"
          git config --global user.name "10upbot on GitHub"
          git add -f vendor && git commit -m "Add composer dependencies"
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: ${{ secrets.WORDPRESS_SLUG }}
